Imports Namcore_Studio.EventLogging
Imports Namcore_Studio.Basics
Imports Namcore_Studio.GlobalVariables
Imports Namcore_Studio.CommandHandler
Public Class BasicsHandler
    Private Shared temp_result As String
    Public Shared Sub GetBasicCharacterInformation(ByVal characterGuid As Integer, ByVal setId As Integer)
        LogAppend("Loading basic character information for characterGuid: " & characterGuid.ToString & " and setId: " & setId.ToString, "BasicHandler_GetBasicCharacterInformation", True)
        Select Case sourceCore
            Case "arcemu"
                loadAtArcemu(characterGuid, setId)
            Case "trinity"

            Case "mangos"

            Case Else

        End Select

    End Sub
    Private Shared Sub loadAtArcemu(ByVal charguid As Integer, ByVal tar_setId As Integer)

        'Character Table
        temp_result = runSQLCommand_int("SELECT " & char_race_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'").ToString
        SetTemporaryCharacterInformation("@character_race", temp_result, tar_setId)
        LogAppend("Loaded character race info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_race_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_class", temp_result, tar_setId)
        LogAppend("Loaded character class info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_gender_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_gender", temp_result, tar_setId)
        LogAppend("Loaded character gender info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_level_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_level", temp_result, tar_setId)
        LogAppend("Loaded character level info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_name_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_accountId_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_accountId", temp_result, tar_setId)
        LogAppend("Loaded character accountId info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_xp_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_gold_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_playerBytes_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_playerBytes2_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_playerFlags_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_posX_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_posY_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_posZ_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_map_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_instanceId_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_orientation_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_taximask_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_cinematic_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_totaltime_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_stableSlots_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_zone_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_arenaPoints_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_totalHonorPoints_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_totalKills_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_chosenTitle_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_watchedFaction_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_health_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_speccount_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_activeSpec_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_exploredZones_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_knownTitles_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_arcemuTalentPoints_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_finishedQuests_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_customFaction_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_bindmapid_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_bindzoneid_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_bindposX_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_bindposY_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & char_bindposZ_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)


        'Account Table
        temp_result = runSQLCommand_int("SELECT " & acc_name_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & acc_arcemuPass_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & acc_passHash_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & acc_arcemuFlags_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & acc_locale_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
        temp_result = runSQLCommand_int("SELECT " & acc_arcemuGmLevel_columnname & " FROM " & character_tablename & " WHERE " & char_guid_columnname & "='" & charguid & "'")
        SetTemporaryCharacterInformation("@character_name", temp_result, tar_setId)
        LogAppend("Loaded character name info for characterGuid: " & charguid.ToString & " and setId: " & tar_setId.ToString & " // result is: " & temp_result, "BasicHandler_LoadAtArcemu", True)
    End Sub

End Class
