
Module Main
    Public AchievementCatDeDic As Dictionary(Of Integer, String())
    Public AchievementCatEnDic As Dictionary(Of Integer, String())
    Public AchievementDeDic As Dictionary(Of Integer, String())
    Public AchievementEnDic As Dictionary(Of Integer, String())
    Public EnchantmentDeDic As Dictionary(Of Integer, String())
    Public EnchantmentEnDic As Dictionary(Of Integer, String())
    Public FactionDeDic As Dictionary(Of Integer, String())
    Public FactionEnDic As Dictionary(Of Integer, String())
    Public GlyphProps0Dic As Dictionary(Of Integer, String())
    Public GlyphProps1Dic As Dictionary(Of Integer, String())
    Public GlyphProps2Dic As Dictionary(Of Integer, String())
    Public ItemDic As Dictionary(Of Integer, String())
    Public ItemDisplayDic As Dictionary(Of Integer, String())
    Public ItemSparseDeDic As Dictionary(Of Integer, String())
    Public ItemSparseEnDic As Dictionary(Of Integer, String())
    Public SkillDic As Dictionary(Of Integer, String())
    Public SkillLineAbilityDic As Dictionary(Of Integer, String())
    Public SkillLineDeDic As Dictionary(Of Integer, String())
    Public SkillLineEnDic As Dictionary(Of Integer, String())
    Public SpellDeDic As Dictionary(Of Integer, String())
    Public SpellEnDic As Dictionary(Of Integer, String())
    Public SpellIconDic As Dictionary(Of Integer, String())
    Public SpellLkDic As Dictionary(Of Integer, String())
    Public SplEffectDic As Dictionary(Of Integer, String())
    Sub InitDics()
        AchievementCatDeDic = New Dictionary(Of Integer, String())()
        AchievementCatDeDic.Add(0, {"int", "Id"})
        AchievementCatDeDic.Add(1, {"int", "MainCatId"})
        AchievementCatDeDic.Add(2, {"string", "Name"})

        AchievementCatEnDic = New Dictionary(Of Integer, String())()
        AchievementCatEnDic.Add(0, {"int", "Id"})
        AchievementCatEnDic.Add(1, {"int", "MainCatId"})
        AchievementCatEnDic.Add(2, {"string", "Name"})

        AchievementDeDic = New Dictionary(Of Integer, String())()
        AchievementDeDic.Add(0, {"int", "Id"})
        AchievementDeDic.Add(4, {"string", "Name"})
        AchievementDeDic.Add(5, {"string", "Description"})
        AchievementDeDic.Add(6, {"int", "CategoryId"})
        AchievementDeDic.Add(10, {"int", "SpellId"})

        AchievementEnDic = New Dictionary(Of Integer, String())()
        AchievementEnDic.Add(0, {"int", "Id"})
        AchievementEnDic.Add(4, {"string", "Name"})
        AchievementEnDic.Add(5, {"string", "Description"})
        AchievementEnDic.Add(6, {"int", "CategoryId"})
        AchievementEnDic.Add(10, {"int", "SpellId"})

        EnchantmentDeDic = New Dictionary(Of Integer, String())()
        EnchantmentDeDic.Add(0, {"int", "EffectId"})
        EnchantmentDeDic.Add(11, {"string", "EffectName"})

        EnchantmentEnDic = New Dictionary(Of Integer, String())()
        EnchantmentEnDic.Add(0, {"int", "EffectId"})
        EnchantmentEnDic.Add(11, {"string", "EffectName"})

        FactionDeDic = New Dictionary(Of Integer, String())()
        FactionDeDic.Add(0, {"int", "Id"})
        FactionDeDic.Add(1, {"int", "ReputationIndex"})
        FactionDeDic.Add(23, {"string", "Name"})

        FactionEnDic = New Dictionary(Of Integer, String())()
        FactionEnDic.Add(0, {"int", "Id"})
        FactionEnDic.Add(1, {"int", "ReputationIndex"})
        FactionEnDic.Add(23, {"string", "Name"})

        GlyphProps0Dic = New Dictionary(Of Integer, String())()
        GlyphProps0Dic.Add(0, {"int", "Id"})
        GlyphProps0Dic.Add(1, {"int", "SpellId"})
        GlyphProps0Dic.Add(3, {"int", "Icon"})

        GlyphProps1Dic = New Dictionary(Of Integer, String())()
        GlyphProps1Dic.Add(0, {"int", "Id"})
        GlyphProps1Dic.Add(1, {"int", "SpellId"})
        GlyphProps1Dic.Add(3, {"int", "Icon"})

        GlyphProps2Dic = New Dictionary(Of Integer, String())()
        GlyphProps2Dic.Add(0, {"int", "Id"})
        GlyphProps2Dic.Add(1, {"int", "SpellId"})
        GlyphProps2Dic.Add(3, {"int", "Icon"})

        ItemDic = New Dictionary(Of Integer, String())()
        ItemDic.Add(0, {"int", "Id"})
        ItemDic.Add(1, {"int", "ItemClass"})
        ItemDic.Add(2, {"int", "SubClass"})
        ItemDic.Add(5, {"int", "DisplayId"})

        ItemDisplayDic = New Dictionary(Of Integer, String())()
        ItemDisplayDic.Add(0, {"int", "Id"})
        ItemDisplayDic.Add(5, {"string", "Icon"})

        ItemSparseDeDic = New Dictionary(Of Integer, String())()
        ItemSparseDeDic.Add(0, {"int", "Id"})
        ItemSparseDeDic.Add(1, {"int", "Quality"})
        ItemSparseDeDic.Add(10, {"int", "InventoryType"})
        ItemSparseDeDic.Add(23, {"int", "MaxStack"})
        ItemSparseDeDic.Add(24, {"int", "SlotCount"})
        ItemSparseDeDic.Add(100, {"string", "ItemName"})

        ItemSparseEnDic = New Dictionary(Of Integer, String())()
        ItemSparseEnDic.Add(0, {"int", "Id"})
        ItemSparseEnDic.Add(1, {"int", "Quality"})
        ItemSparseEnDic.Add(10, {"int", "InventoryType"})
        ItemSparseEnDic.Add(23, {"int", "MaxStack"})
        ItemSparseEnDic.Add(24, {"int", "SlotCount"})
        ItemSparseEnDic.Add(100, {"string", "ItemName"})

        SkillDic = New Dictionary(Of Integer, String())()
        SkillDic.Add(0, {"int", "Id"})
        SkillDic.Add(1, {"int", "RefIdSkillLineCategory"})
        SkillDic.Add(2, {"string", "Name"})
        SkillDic.Add(3, {"string", "Description"})
        SkillDic.Add(5, {"string", "RefIdSpellIcon"})
        SkillDic.Add(6, {"string", "Verb"})
        SkillDic.Add(7, {"int", "CanLink"})

        SkillLineAbilityDic = New Dictionary(Of Integer, String())()
        SkillLineAbilityDic.Add(0, {"int", "Id"})
        SkillLineAbilityDic.Add(1, {"int", "SkillId"})
        SkillLineAbilityDic.Add(2, {"int", "SpellId"})
        SkillLineAbilityDic.Add(8, {"int", "MaxSkill"})
        SkillLineAbilityDic.Add(9, {"int", "MinSkill"})

        SkillLineDeDic = New Dictionary(Of Integer, String())()
        SkillLineDeDic.Add(0, {"int", "Id"})
        SkillLineDeDic.Add(2, {"string", "Name"})

        SkillLineEnDic = New Dictionary(Of Integer, String())()
        SkillLineEnDic.Add(0, {"int", "Id"})
        SkillLineEnDic.Add(2, {"string", "Name"})

        SpellDeDic = New Dictionary(Of Integer, String())()
        SpellDeDic.Add(0, {"int", "Id"})
        SpellDeDic.Add(1, {"string", "Attributes"})

        SpellEnDic = New Dictionary(Of Integer, String())()
        SpellEnDic.Add(0, {"int", "Id"})
        SpellEnDic.Add(1, {"string", "Attributes"})

        SpellIconDic = New Dictionary(Of Integer, String())()
        SpellIconDic.Add(0, {"int", "Id"})
        SpellIconDic.Add(1, {"string", "Icon"})

        SpellLkDic = New Dictionary(Of Integer, String())()
        SpellLkDic.Add(0, {"int", "Id"})
        SpellLkDic.Add(108, {"int", "EffectMiscValue_1"})

        SplEffectDic = New Dictionary(Of Integer, String())()
        SplEffectDic.Add(11, {"int", "ItemId"})
        SplEffectDic.Add(13, {"int", "EffectId"})
    End Sub
    Sub Main()
        InitDics()
        ' Dim avTable As DataTable = ReadDb("Achievement.dbc", AvDic)
        Console.Read()

    End Sub

End Module
