'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.32559
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class UserMessages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Namcore_Studio.UserMessages", GetType(UserMessages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Achievement successfully added! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property achievementadded() As String
            Get
                Return ResourceManager.GetString("achievementadded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The player already has this achievement. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property achievementalreadypresent() As String
            Get
                Return ResourceManager.GetString("achievementalreadypresent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Are you sure? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property areyousure() As String
            Get
                Return ResourceManager.GetString("areyousure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Attention ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property attention() As String
            Get
                Return ResourceManager.GetString("attention", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the achievement %avid% from character? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property aus_deleteav() As String
            Get
                Return ResourceManager.GetString("aus_deleteav", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Blood Elf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property bloodelf() As String
            Get
                Return ResourceManager.GetString("bloodelf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You did not set any character name. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property charnamenotset() As String
            Get
                Return ResourceManager.GetString("charnamenotset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Character not found! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property charnotfound() As String
            Get
                Return ResourceManager.GetString("charnotfound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Connect to source server ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property connecttosource() As String
            Get
                Return ResourceManager.GetString("connecttosource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Connect to target server ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property connecttotarget() As String
            Get
                Return ResourceManager.GetString("connecttotarget", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Death Knight ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property deathknight() As String
            Get
                Return ResourceManager.GetString("deathknight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the selected accounts? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property deleteacc() As String
            Get
                Return ResourceManager.GetString("deleteacc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the selected characters? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property deletechar() As String
            Get
                Return ResourceManager.GetString("deletechar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the selected item? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property deleteitem() As String
            Get
                Return ResourceManager.GetString("deleteitem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Draenei ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property draenei() As String
            Get
                Return ResourceManager.GetString("draenei", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druid ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property druid() As String
            Get
                Return ResourceManager.GetString("druid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dwarf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property dwarf() As String
            Get
                Return ResourceManager.GetString("dwarf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property errorbox() As String
            Get
                Return ResourceManager.GetString("errorbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Faction successfully added! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property factionadded() As String
            Get
                Return ResourceManager.GetString("factionadded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The player already has reputation at this faction! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property factionalreadypresent() As String
            Get
                Return ResourceManager.GetString("factionalreadypresent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Female ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property female() As String
            Get
                Return ResourceManager.GetString("female", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die This is not a valid glyph! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property glyphnotfound() As String
            Get
                Return ResourceManager.GetString("glyphnotfound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gnome ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property gnome() As String
            Get
                Return ResourceManager.GetString("gnome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Goblin ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property goblin() As String
            Get
                Return ResourceManager.GetString("goblin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Human ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property human() As String
            Get
                Return ResourceManager.GetString("human", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hunter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property hunter() As String
            Get
                Return ResourceManager.GetString("hunter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Invalid achievement id! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property invalidavid() As String
            Get
                Return ResourceManager.GetString("invalidavid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Invalid faction id! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property invalidrepid() As String
            Get
                Return ResourceManager.GetString("invalidrepid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Entered URL is not valid! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property invalidurl() As String
            Get
                Return ResourceManager.GetString("invalidurl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The class of the entered item does not match the source item class! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property itemclassinvalid() As String
            Get
                Return ResourceManager.GetString("itemclassinvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mage ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mage() As String
            Get
                Return ResourceManager.GetString("mage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Male ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property male() As String
            Get
                Return ResourceManager.GetString("male", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Monk ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Monk() As String
            Get
                Return ResourceManager.GetString("Monk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Night Elf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property nightelf() As String
            Get
                Return ResourceManager.GetString("nightelf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You did not enter any accounts! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property noaccentered() As String
            Get
                Return ResourceManager.GetString("noaccentered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Orc ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property orc() As String
            Get
                Return ResourceManager.GetString("orc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Paladin ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property paladin() As String
            Get
                Return ResourceManager.GetString("paladin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pandaren ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property pandaren() As String
            Get
                Return ResourceManager.GetString("pandaren", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Priest ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property priest() As String
            Get
                Return ResourceManager.GetString("priest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You did not set any realm name. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property realmnamenotset() As String
            Get
                Return ResourceManager.GetString("realmnamenotset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You did not select any Battle.net region. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property regionnotset() As String
            Get
                Return ResourceManager.GetString("regionnotset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rogue ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property rogue() As String
            Get
                Return ResourceManager.GetString("rogue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Shaman ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property shaman() As String
            Get
                Return ResourceManager.GetString("shaman", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stranger ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property standing_0() As String
            Get
                Return ResourceManager.GetString("standing_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Acquaintance ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property standing_1() As String
            Get
                Return ResourceManager.GetString("standing_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unfriendly ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property standing_2() As String
            Get
                Return ResourceManager.GetString("standing_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Neutral ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property standing_3() As String
            Get
                Return ResourceManager.GetString("standing_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Friendly ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property standing_4() As String
            Get
                Return ResourceManager.GetString("standing_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Honored ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property standing_5() As String
            Get
                Return ResourceManager.GetString("standing_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Revered ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property standing_6() As String
            Get
                Return ResourceManager.GetString("standing_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Exalted ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property standing_7() As String
            Get
                Return ResourceManager.GetString("standing_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat0() As String
            Get
                Return ResourceManager.GetString("subcat0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Eastern Kingdoms ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14777() As String
            Get
                Return ResourceManager.GetString("subcat14777", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kalimdor ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14778() As String
            Get
                Return ResourceManager.GetString("subcat14778", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Outland ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14779() As String
            Get
                Return ResourceManager.GetString("subcat14779", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Northrend ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14780() As String
            Get
                Return ResourceManager.GetString("subcat14780", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alterac Vlley ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14801() As String
            Get
                Return ResourceManager.GetString("subcat14801", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Arathi Basin ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14802() As String
            Get
                Return ResourceManager.GetString("subcat14802", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Eye of the Storm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14803() As String
            Get
                Return ResourceManager.GetString("subcat14803", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Warsong Gulch ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14804() As String
            Get
                Return ResourceManager.GetString("subcat14804", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The Burning Crusade ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14805() As String
            Get
                Return ResourceManager.GetString("subcat14805", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Lich King Dungeon ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14806() As String
            Get
                Return ResourceManager.GetString("subcat14806", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Classic ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14808() As String
            Get
                Return ResourceManager.GetString("subcat14808", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Eastern Kingdoms ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14861() As String
            Get
                Return ResourceManager.GetString("subcat14861", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Outland ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14862() As String
            Get
                Return ResourceManager.GetString("subcat14862", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Northrend ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14863() As String
            Get
                Return ResourceManager.GetString("subcat14863", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Classic ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14864() As String
            Get
                Return ResourceManager.GetString("subcat14864", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The Burning Crusade ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14865() As String
            Get
                Return ResourceManager.GetString("subcat14865", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wrath of the Lich King ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14866() As String
            Get
                Return ResourceManager.GetString("subcat14866", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Strand of the Ancients ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14881() As String
            Get
                Return ResourceManager.GetString("subcat14881", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wintergasp ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14901() As String
            Get
                Return ResourceManager.GetString("subcat14901", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Lich King Raid ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14922() As String
            Get
                Return ResourceManager.GetString("subcat14922", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Argent Tournament ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14941() As String
            Get
                Return ResourceManager.GetString("subcat14941", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pilgrim&apos;s Bounty ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat14981() As String
            Get
                Return ResourceManager.GetString("subcat14981", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Isle of Conquest ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15003() As String
            Get
                Return ResourceManager.GetString("subcat15003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cataclysm Dungeon ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15067() As String
            Get
                Return ResourceManager.GetString("subcat15067", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cataclysm Raid ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15068() As String
            Get
                Return ResourceManager.GetString("subcat15068", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cataclysm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15069() As String
            Get
                Return ResourceManager.GetString("subcat15069", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cataclysm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15070() As String
            Get
                Return ResourceManager.GetString("subcat15070", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Archaeology ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15071() As String
            Get
                Return ResourceManager.GetString("subcat15071", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cataclysm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15072() As String
            Get
                Return ResourceManager.GetString("subcat15072", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Battle for Gilneas ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15073() As String
            Get
                Return ResourceManager.GetString("subcat15073", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Twin Peaks ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15074() As String
            Get
                Return ResourceManager.GetString("subcat15074", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tol Barad ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15075() As String
            Get
                Return ResourceManager.GetString("subcat15075", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kalimdor ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15081() As String
            Get
                Return ResourceManager.GetString("subcat15081", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rated Battleground ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15092() As String
            Get
                Return ResourceManager.GetString("subcat15092", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Darkmoon Faire ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15101() As String
            Get
                Return ResourceManager.GetString("subcat15101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pandaria Dungeon ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15106() As String
            Get
                Return ResourceManager.GetString("subcat15106", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pandaria Raid ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15107() As String
            Get
                Return ResourceManager.GetString("subcat15107", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pandaria ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15110() As String
            Get
                Return ResourceManager.GetString("subcat15110", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pandaria ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15113() As String
            Get
                Return ResourceManager.GetString("subcat15113", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pandaria ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15114() As String
            Get
                Return ResourceManager.GetString("subcat15114", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dungeon Challenge ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15115() As String
            Get
                Return ResourceManager.GetString("subcat15115", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Collect ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15118() As String
            Get
                Return ResourceManager.GetString("subcat15118", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Battle ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15119() As String
            Get
                Return ResourceManager.GetString("subcat15119", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Level ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15120() As String
            Get
                Return ResourceManager.GetString("subcat15120", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Silvershard Mines ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15162() As String
            Get
                Return ResourceManager.GetString("subcat15162", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Temple of Kotmogu ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15163() As String
            Get
                Return ResourceManager.GetString("subcat15163", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Brawler&apos;s Guild ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15202() As String
            Get
                Return ResourceManager.GetString("subcat15202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Deepwind Gorge ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat15218() As String
            Get
                Return ResourceManager.GetString("subcat15218", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Winter Veil ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat156() As String
            Get
                Return ResourceManager.GetString("subcat156", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hallow&apos;s End ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat158() As String
            Get
                Return ResourceManager.GetString("subcat158", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Noblegarden ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat159() As String
            Get
                Return ResourceManager.GetString("subcat159", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Lunar Festival ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat160() As String
            Get
                Return ResourceManager.GetString("subcat160", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Midsummer ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat161() As String
            Get
                Return ResourceManager.GetString("subcat161", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Brewfest ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat162() As String
            Get
                Return ResourceManager.GetString("subcat162", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Children&apos;s Week ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat163() As String
            Get
                Return ResourceManager.GetString("subcat163", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Arena ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat165() As String
            Get
                Return ResourceManager.GetString("subcat165", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cooking ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat170() As String
            Get
                Return ResourceManager.GetString("subcat170", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fishing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat171() As String
            Get
                Return ResourceManager.GetString("subcat171", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die First Aid ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat172() As String
            Get
                Return ResourceManager.GetString("subcat172", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Love is in the Air ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property subcat187() As String
            Get
                Return ResourceManager.GetString("subcat187", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tauren ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property tauren() As String
            Get
                Return ResourceManager.GetString("tauren", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Troll ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property troll() As String
            Get
                Return ResourceManager.GetString("troll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Undead ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property undead() As String
            Get
                Return ResourceManager.GetString("undead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You did not enter a correct url. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property urlnotset() As String
            Get
                Return ResourceManager.GetString("urlnotset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Warlock ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property warlock() As String
            Get
                Return ResourceManager.GetString("warlock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Warrior ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property warrior() As String
            Get
                Return ResourceManager.GetString("warrior", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Worgen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property worgen() As String
            Get
                Return ResourceManager.GetString("worgen", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
