'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.32559
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class UserMessages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Namcore_Studio.UserMessages", GetType(UserMessages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Are you sure? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property areyousure() As String
            Get
                Return ResourceManager.GetString("areyousure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Attention ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property attention() As String
            Get
                Return ResourceManager.GetString("attention", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Blood Elf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property bloodelf() As String
            Get
                Return ResourceManager.GetString("bloodelf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You did not set any character name. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property charnamenotset() As String
            Get
                Return ResourceManager.GetString("charnamenotset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Character not found! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property charnotfound() As String
            Get
                Return ResourceManager.GetString("charnotfound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Connect to source server ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property connecttosource() As String
            Get
                Return ResourceManager.GetString("connecttosource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Connect to target server ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property connecttotarget() As String
            Get
                Return ResourceManager.GetString("connecttotarget", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Death Knight ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property deathknight() As String
            Get
                Return ResourceManager.GetString("deathknight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the selected accounts? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property deleteacc() As String
            Get
                Return ResourceManager.GetString("deleteacc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the selected characters? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property deletechar() As String
            Get
                Return ResourceManager.GetString("deletechar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the selected item? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property deleteitem() As String
            Get
                Return ResourceManager.GetString("deleteitem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Draenei ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property draenei() As String
            Get
                Return ResourceManager.GetString("draenei", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druid ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property druid() As String
            Get
                Return ResourceManager.GetString("druid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dwarf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property dwarf() As String
            Get
                Return ResourceManager.GetString("dwarf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property errorbox() As String
            Get
                Return ResourceManager.GetString("errorbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Female ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property female() As String
            Get
                Return ResourceManager.GetString("female", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die This is not a valid glyph! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property glyphnotfound() As String
            Get
                Return ResourceManager.GetString("glyphnotfound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gnome ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property gnome() As String
            Get
                Return ResourceManager.GetString("gnome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Goblin ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property goblin() As String
            Get
                Return ResourceManager.GetString("goblin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Human ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property human() As String
            Get
                Return ResourceManager.GetString("human", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hunter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property hunter() As String
            Get
                Return ResourceManager.GetString("hunter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Entered URL is not valid! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property invalidurl() As String
            Get
                Return ResourceManager.GetString("invalidurl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The class of the entered item does not match the source item class! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property itemclassinvalid() As String
            Get
                Return ResourceManager.GetString("itemclassinvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mage ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property mage() As String
            Get
                Return ResourceManager.GetString("mage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Male ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property male() As String
            Get
                Return ResourceManager.GetString("male", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Night Elf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property nightelf() As String
            Get
                Return ResourceManager.GetString("nightelf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You did not enter any accounts! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property noaccentered() As String
            Get
                Return ResourceManager.GetString("noaccentered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Orc ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property orc() As String
            Get
                Return ResourceManager.GetString("orc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Paladin ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property paladin() As String
            Get
                Return ResourceManager.GetString("paladin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Priest ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property priest() As String
            Get
                Return ResourceManager.GetString("priest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You did not set any realm name. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property realmnamenotset() As String
            Get
                Return ResourceManager.GetString("realmnamenotset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You did not select any Battle.net region. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property regionnotset() As String
            Get
                Return ResourceManager.GetString("regionnotset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rogue ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property rogue() As String
            Get
                Return ResourceManager.GetString("rogue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Shaman ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property shaman() As String
            Get
                Return ResourceManager.GetString("shaman", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stranger ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property standing_0() As String
            Get
                Return ResourceManager.GetString("standing_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Acquaintance ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property standing_1() As String
            Get
                Return ResourceManager.GetString("standing_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unfriendly ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property standing_2() As String
            Get
                Return ResourceManager.GetString("standing_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Neutral ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property standing_3() As String
            Get
                Return ResourceManager.GetString("standing_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Friendly ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property standing_4() As String
            Get
                Return ResourceManager.GetString("standing_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Honored ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property standing_5() As String
            Get
                Return ResourceManager.GetString("standing_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Revered ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property standing_6() As String
            Get
                Return ResourceManager.GetString("standing_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Exalted ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property standing_7() As String
            Get
                Return ResourceManager.GetString("standing_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tauren ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property tauren() As String
            Get
                Return ResourceManager.GetString("tauren", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Troll ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property troll() As String
            Get
                Return ResourceManager.GetString("troll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Undead ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property undead() As String
            Get
                Return ResourceManager.GetString("undead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You did not enter a correct url. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property urlnotset() As String
            Get
                Return ResourceManager.GetString("urlnotset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Warlock ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property warlock() As String
            Get
                Return ResourceManager.GetString("warlock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Warrior ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property warrior() As String
            Get
                Return ResourceManager.GetString("warrior", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Worgen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property worgen() As String
            Get
                Return ResourceManager.GetString("worgen", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
