'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.18052
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("libnc.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die avid;avname;avdesc;avcat;
        '''6;Stufe 10;Erreicht Stufe 10.;92;
        '''7;Stufe 20;Erreicht Stufe 20.;92;
        '''8;Stufe 30;Erreicht Stufe 30.;92;
        '''9;Stufe 40;Erreicht Stufe 40.;92;
        '''10;Stufe 50;Erreicht Stufe 50.;92;
        '''11;Stufe 60;Erreicht Stufe 60.;92;
        '''12;Stufe 70;Erreicht Stufe 70.;92;
        '''13;Stufe 80;Erreicht Stufe 80.;92;
        '''15;Jede Menge Haustiere;Sammelt 15 einzigartige Haustiere.;15118;
        '''16;Hat jemand ein Veilchen bestellt?;Erreicht eine unbewaffnete Fertigkeit von 400.;81;
        '''31;Alltägliches;Schließt an fünf aufeinander  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property av_de() As String
            Get
                Return ResourceManager.GetString("av_de", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die catid;catmainid;catname
        '''1;-1;Statistiken
        '''21;1;Spieler gegen Spieler
        '''81;-1;Heldentaten
        '''92;-1;Allgemein
        '''95;-1;Spieler gegen Spieler
        '''96;-1;Quests
        '''97;-1;Erkundung
        '''122;1;Tode
        '''123;122;Arenen
        '''124;122;Schlachtfelder
        '''125;122;Dungeons
        '''126;122;Welt
        '''127;122;Wiederbelebung
        '''128;1;Siege
        '''130;1;Charakter
        '''131;1;Körpersprache
        '''132;1;Fertigkeiten
        '''133;1;Quests
        '''134;1;Reise
        '''135;128;Kreaturen
        '''136;128;Ehrenhafte Siege
        '''137;128;Todesstöße
        '''140;130;Vermögen
        '''141;1;Kampf
        '''145;130;Verbrauchsgüter
        '''147;130;Ruf
        '''152;2 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property avcat_de() As String
            Get
                Return ResourceManager.GetString("avcat_de", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die id;spellid;iconname
        '''6;3268;Achievement_Level_10
        '''7;3269;Achievement_Level_20
        '''8;3270;Achievement_Level_30
        '''9;3271;Achievement_Level_40
        '''10;3272;Achievement_Level_50
        '''11;3273;Achievement_Level_60
        '''12;3274;Achievement_Level_70
        '''13;3275;Achievement_Level_80
        '''15;1522;INV_Box_PetCarrier_01
        '''16;1997;Ability_Warrior_SecondWind
        '''31;3481;Achievement_Quests_Completed_Daily_x5
        '''32;3415;Achievement_Quests_Completed_07
        '''33;3336;Achievement_Zone_BoreanTundra_07
        '''34;3337;Achievement_Zone_HowlingFjord_07
        '''35;3338;Achievem [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property avicon() As String
            Get
                Return ResourceManager.GetString("avicon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die avid;maincatid
        '''5445;0
        '''5447;0
        '''6133;0
        '''7324;0
        '''1042;1
        '''1045;1
        '''1047;1
        '''1065;1
        '''1066;1
        '''1067;1
        '''110;1
        '''1102;1
        '''1103;1
        '''1104;1
        '''1149;1
        '''1197;1
        '''1198;1
        '''1199;1
        '''1200;1
        '''1201;1
        '''1339;1
        '''1462;1
        '''1464;1
        '''1465;1
        '''1467;1
        '''1485;1
        '''1501;1
        '''1756;1
        '''1759;1
        '''1760;1
        '''1768;1
        '''1770;1
        '''1771;1
        '''1772;1
        '''189;1
        '''193;1
        '''197;1
        '''198;1
        '''2277;1
        '''3018;1
        '''318;1
        '''349;1
        '''350;1
        '''353;1
        '''4456;1
        '''4556;1
        '''4729;1
        '''4730;1
        '''527;1
        '''528;1
        '''60;1
        '''7223;1
        '''7224;1
        '''7240;1
        '''7241;1
        '''7242;1
        '''7243;1
        '''7244;1
        '''7245;1
        '''7246;1
        '''7247;1
        '''759;1
        '''8278;1
        '''8286;1 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property avmaincat() As String
            Get
                Return ResourceManager.GetString("avmaincat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die id;description
        '''17;Martinsfuror
        '''25;Abgenutztes Kurzschwert
        '''35;Gebogener Stab
        '''36;Abgenutzter Streitkolben
        '''37;Abgenutzte Axt
        '''38;Rekrutenhemd
        '''39;Rekrutenhose
        '''40;Rekrutenstiefel
        '''43;Knappenstiefel
        '''44;Knappenhose
        '''45;Knappenhemd
        '''47;Straßenräuberschuhe
        '''48;Straßenräuberhose
        '''49;Straßenräuberhemd
        '''51;Neophytenstiefel
        '''52;Neophytenhose
        '''53;Neophytenhemd
        '''55;Lehrlingsstiefel
        '''56;Lehrlingsrobe
        '''57;Akolythenrobe
        '''59;Akolythenschuhe
        '''60;Mehrlagige Tunika
        '''61;Zwergische Lederhose
        '''79;Zwergische Stoffkniehose
        '''8 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property dbc_itemsparse_de() As String
            Get
                Return ResourceManager.GetString("dbc_itemsparse_de", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die effectid;effectname
        '''1;Felsbeißer 3
        '''2;Frostbrand
        '''3;Flammenzunge 3
        '''4;Flammenzunge 2
        '''5;Flammenzunge
        '''6;Felsbeißer 2
        '''7;Tödliches Gift
        '''8;Tödliches Gift II
        '''9;Gift (15 Schaden)
        '''10;Gift (20 Schaden)
        '''11;Gift (25 Schaden)
        '''12;Frostbrand 2
        '''13;Geschärft (+3 Schaden)
        '''14;Geschärft (+4 Schaden)
        '''15;Verstärkt (+8 Rüstung)
        '''16;Verstärkt (+16 Rüstung)
        '''17;Verstärkt (+24 Rüstung)
        '''18;Verstärkt (+32 Rüstung)
        '''19;Beschwert (+2 Schaden)
        '''20;Beschwert (+3 Schaden)
        '''21;Beschwert (+4 Schaden)
        '''22;Verkrüppelungsgift
        '''23; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property enchant_name_de() As String
            Get
                Return ResourceManager.GetString("enchant_name_de", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die effectid;effectname
        '''1;Rockbiter 3
        '''2;Frostbrand
        '''3;Flametongue 3
        '''4;Flametongue 2
        '''5;Flametongue
        '''6;Rockbiter 2
        '''7;Deadly Poison
        '''8;Deadly Poison II
        '''9;Poison (15 Dmg)
        '''10;Poison (20 Dmg)
        '''11;Poison (25 Dmg)
        '''12;Frostbrand 2
        '''13;Sharpened (+3 Damage)
        '''14;Sharpened (+4 Damage)
        '''15;Reinforced (+8 Armor)
        '''16;Reinforced (+16 Armor)
        '''17;Reinforced (+24 Armor)
        '''18;Reinforced (+32 Armor)
        '''19;Weighted (+2 Damage)
        '''20;Weighted (+3 Damage)
        '''21;Weighted (+4 Damage)
        '''22;Crippling Poison
        '''23;Mind-numbing Poison II
        '''24; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property enchant_name_en() As String
            Get
                Return ResourceManager.GetString("enchant_name_en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die factionid;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;16;17;18;19;20;21;22;23;24;25;26;27
        '''1;-1.#QNAN0;0;0;0;0;0;0;0;0;0;0.000000;0;0;0;0;;;0;1.000.000;1.000.000;5;5;SPIELER, Mensch;;0;0;
        '''2;-1.#QNAN0;0;0;0;0;0;0;0;0;0;0.000000;0;0;0;0;;;0;1.000.000;1.000.000;5;5;SPIELER, Orc;;0;0;
        '''3;-1.#QNAN0;0;0;0;0;0;0;0;0;0;0.000000;0;0;0;0;;;0;1.000.000;1.000.000;5;5;SPIELER, Zwerg;;0;0;
        '''4;-1.#QNAN0;0;0;0;0;0;0;0;0;0;0.000000;0;0;0;0;;;0;1.000.000;1.000.000;5;5;SPIELER, Nachtelf;;0;0;
        '''5;-1.#QNAN0;0;0;0;0;0;0;0;0;0;0.000000; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property FactionDE() As String
            Get
                Return ResourceManager.GetString("FactionDE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;entry&gt;2&lt;/entry&gt;&lt;spell&gt;52084&lt;/spell&gt;&lt;entry2&gt;2&lt;/entry2&gt;&lt;spell2&gt;52084&lt;/spell2&gt;
        '''&lt;entry&gt;21&lt;/entry&gt;&lt;spell&gt;12320&lt;/spell&gt;&lt;entry2&gt;21&lt;/entry2&gt;&lt;spell2&gt;12320&lt;/spell2&gt;
        '''&lt;entry&gt;22&lt;/entry&gt;&lt;spell&gt;12297&lt;/spell&gt;&lt;entry2&gt;22&lt;/entry2&gt;&lt;spell2&gt;12297&lt;/spell2&gt;
        '''&lt;entry&gt;61&lt;/entry&gt;&lt;spell&gt;46831&lt;/spell&gt;&lt;entry2&gt;61&lt;/entry2&gt;&lt;spell2&gt;46831&lt;/spell2&gt;
        '''&lt;entry&gt;81&lt;/entry&gt;&lt;spell&gt;52084&lt;/spell&gt;&lt;entry2&gt;81&lt;/entry2&gt;&lt;spell2&gt;52084&lt;/spell2&gt;
        '''&lt;entry&gt;82&lt;/entry&gt;&lt;spell&gt;52085&lt;/spell&gt;&lt;entry2&gt;82&lt;/entry2&gt;&lt;spell2&gt;52085&lt;/spell2&gt;
        '''&lt;entry&gt;101&lt;/entry&gt;&lt;spell&gt;0&lt;/spell&gt; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property glyphproperties_335() As String
            Get
                Return ResourceManager.GetString("glyphproperties_335", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;entry&gt;161&lt;/entry&gt;&lt;spell&gt;54810&lt;/spell&gt;&lt;entry2&gt;161&lt;/entry2&gt;&lt;spell2&gt;54810&lt;/spell2&gt;
        '''&lt;entry&gt;162&lt;/entry&gt;&lt;spell&gt;54811&lt;/spell&gt;&lt;entry2&gt;162&lt;/entry2&gt;&lt;spell2&gt;54811&lt;/spell2&gt;
        '''&lt;entry&gt;163&lt;/entry&gt;&lt;spell&gt;54812&lt;/spell&gt;&lt;entry2&gt;163&lt;/entry2&gt;&lt;spell2&gt;54812&lt;/spell2&gt;
        '''&lt;entry&gt;164&lt;/entry&gt;&lt;spell&gt;54813&lt;/spell&gt;&lt;entry2&gt;164&lt;/entry2&gt;&lt;spell2&gt;54813&lt;/spell2&gt;
        '''&lt;entry&gt;165&lt;/entry&gt;&lt;spell&gt;54815&lt;/spell&gt;&lt;entry2&gt;165&lt;/entry2&gt;&lt;spell2&gt;54815&lt;/spell2&gt;
        '''&lt;entry&gt;166&lt;/entry&gt;&lt;spell&gt;54818&lt;/spell&gt;&lt;entry2&gt;166&lt;/entry2&gt;&lt;spell2&gt;54818&lt;/spell2&gt;
        '''&lt;entry&gt;167&lt;/entry&gt;&lt;s [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property glyphproperties_434() As String
            Get
                Return ResourceManager.GetString("glyphproperties_434", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die itemid;iconname
        '''224;INV_Jewelry_Ring_03
        '''233;INV_Boots_01
        '''242;INV_Boots_01
        '''245;INV_Boots_01
        '''249;INV_Boots_01
        '''253;INV_Boots_01
        '''257;INV_Boots_01
        '''261;INV_Boots_01
        '''292;INV_Potion_08
        '''295;INV_Boots_02
        '''302;INV_Boots_01
        '''310;INV_Belt_01
        '''311;INV_Boots_01
        '''362;INV_Misc_Bag_01
        '''365;INV_Pants_02
        '''368;INV_Pants_02
        '''369;INV_Shirt_01
        '''370;INV_Pants_02
        '''371;INV_Shirt_01
        '''372;INV_Pants_02
        '''373;INV_Shirt_01
        '''374;INV_Pants_02
        '''383;INV_Shirt_01
        '''386;INV_Pants_02
        '''387;INV_Shirt_01
        '''392;INV_Pants_02
        '''393;INV_Shirt_01        ''' [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property ItemDisplayInfo() As String
            Get
                Return ResourceManager.GetString("ItemDisplayInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Id;Title
        '''1;Kanrethad&apos;s Quest
        '''2;Sharptalon&apos;s Claw
        '''5;Jitters&apos; Growling Gut
        '''6;Bounty on Garrick Padfoot
        '''7;[DEPRECATED] Kobold Camp Cleanup
        '''8;A Rogue&apos;s Deal
        '''9;The Killing Fields
        '''10;The Scrimshank Redemption
        '''11;Riverpaw Gnoll Bounty
        '''12;The People&apos;s Militia
        '''13;The People&apos;s Militia
        '''14;The People&apos;s Militia
        '''15;[DEPRECATED] Investigate Echo Ridge
        '''16;Give Gerard a Drink
        '''17;Uldaman Reagent Run
        '''18;Brotherhood of Thieves
        '''19;Tharil&apos;zun
        '''20;Blackrock Menace
        '''21;[DEPRECATED] Skirmish at Echo Ridge
        '''22;Goret [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property questname() As String
            Get
                Return ResourceManager.GetString("questname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Public ReadOnly Property SkillLineDE() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SkillLineDE", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Public ReadOnly Property SpellDE() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SpellDE", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die TalentId;Rang1;Rang2;Rang3;Rang4;Rang5
        '''27;11078;11080;0;0;0
        '''1141;18459;18460;54734;0;0
        '''26;11069;12338;12339;12340;12341
        '''34;11119;11120;12846;12847;12848
        '''2212;54747;54749;0;0;0
        '''31;11108;12349;12350;0;0
        '''28;11100;12353;0;0;0
        '''30;11103;12357;12358;0;0
        '''29;11366;0;0;0;0
        '''23;11083;12351;0;0;0
        '''25;11095;12872;12873;0;0
        '''24;11094;13043;0;0;0
        '''1639;29074;29075;29076;0;0
        '''1730;31638;31639;31640;0;0
        '''33;11115;11367;11368;0;0
        '''32;11113;0;0;0;0
        '''1731;31641;31642;0;0;0
        '''35;11124;12378;12398;12399;12400
        '''1733;34293 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property talent() As String
            Get
                Return ResourceManager.GetString("talent", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
