'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.34014
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NCFramework.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bt_close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bt_close_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_close_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bt_minimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_minimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bt_minimize_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_minimize_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Death Knight ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_CLASS_DEATHKNIGHT() As String
            Get
                Return ResourceManager.GetString("CHAR_CLASS_DEATHKNIGHT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druid ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_CLASS_DRUID() As String
            Get
                Return ResourceManager.GetString("CHAR_CLASS_DRUID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hunter ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_CLASS_HUNTER() As String
            Get
                Return ResourceManager.GetString("CHAR_CLASS_HUNTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mage ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_CLASS_MAGE() As String
            Get
                Return ResourceManager.GetString("CHAR_CLASS_MAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Monk ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_CLASS_MONK() As String
            Get
                Return ResourceManager.GetString("CHAR_CLASS_MONK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Paladin ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_CLASS_PALADIN() As String
            Get
                Return ResourceManager.GetString("CHAR_CLASS_PALADIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Priest ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_CLASS_PRIEST() As String
            Get
                Return ResourceManager.GetString("CHAR_CLASS_PRIEST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Rogue ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_CLASS_ROGUE() As String
            Get
                Return ResourceManager.GetString("CHAR_CLASS_ROGUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Shaman ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_CLASS_SHAMAN() As String
            Get
                Return ResourceManager.GetString("CHAR_CLASS_SHAMAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Warlock ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_CLASS_WARLOCK() As String
            Get
                Return ResourceManager.GetString("CHAR_CLASS_WARLOCK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Warrior ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_CLASS_WARRIOR() As String
            Get
                Return ResourceManager.GetString("CHAR_CLASS_WARRIOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Female ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_GENDER_FEMALE() As String
            Get
                Return ResourceManager.GetString("CHAR_GENDER_FEMALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Male ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_GENDER_MALE() As String
            Get
                Return ResourceManager.GetString("CHAR_GENDER_MALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Blood Elf ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_RACE_BLOODELF() As String
            Get
                Return ResourceManager.GetString("CHAR_RACE_BLOODELF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Draenei ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_RACE_DRAENEI() As String
            Get
                Return ResourceManager.GetString("CHAR_RACE_DRAENEI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dwarf ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_RACE_DWARF() As String
            Get
                Return ResourceManager.GetString("CHAR_RACE_DWARF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gnome ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_RACE_GNOME() As String
            Get
                Return ResourceManager.GetString("CHAR_RACE_GNOME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Goblin ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_RACE_GOBLIN() As String
            Get
                Return ResourceManager.GetString("CHAR_RACE_GOBLIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Human ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_RACE_HUMAN() As String
            Get
                Return ResourceManager.GetString("CHAR_RACE_HUMAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Night Elf ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_RACE_NIGHTELF() As String
            Get
                Return ResourceManager.GetString("CHAR_RACE_NIGHTELF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Orc ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_RACE_ORC() As String
            Get
                Return ResourceManager.GetString("CHAR_RACE_ORC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pandaren ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_RACE_PANDAREN() As String
            Get
                Return ResourceManager.GetString("CHAR_RACE_PANDAREN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tauren ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_RACE_TAUREN() As String
            Get
                Return ResourceManager.GetString("CHAR_RACE_TAUREN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Troll ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_RACE_TROLL() As String
            Get
                Return ResourceManager.GetString("CHAR_RACE_TROLL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Undead ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_RACE_UNDEAD() As String
            Get
                Return ResourceManager.GetString("CHAR_RACE_UNDEAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Worgen ähnelt.
        '''</summary>
        Public ReadOnly Property CHAR_RACE_WORGEN() As String
            Get
                Return ResourceManager.GetString("CHAR_RACE_WORGEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property empty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("empty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property highlight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("highlight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property HUD_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HUD_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property INV_Misc_QuestionMark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INV_Misc_QuestionMark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        '''</summary>
        Public ReadOnly Property MISC_PROFADD() As String
            Get
                Return ResourceManager.GetString("MISC_PROFADD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Learn ähnelt.
        '''</summary>
        Public ReadOnly Property MISC_PROFLEARN() As String
            Get
                Return ResourceManager.GetString("MISC_PROFLEARN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Learn all ähnelt.
        '''</summary>
        Public ReadOnly Property MISC_PROFLEARNALL() As String
            Get
                Return ResourceManager.GetString("MISC_PROFLEARNALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Learned ähnelt.
        '''</summary>
        Public ReadOnly Property MISC_PROFLEARNED() As String
            Get
                Return ResourceManager.GetString("MISC_PROFLEARNED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Not Yet Learned ähnelt.
        '''</summary>
        Public ReadOnly Property MISC_PROFNYLEARNED() As String
            Get
                Return ResourceManager.GetString("MISC_PROFNYLEARNED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  results! ähnelt.
        '''</summary>
        Public ReadOnly Property MISC_PROFRESULTS() As String
            Get
                Return ResourceManager.GetString("MISC_PROFRESULTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unlearn ähnelt.
        '''</summary>
        Public ReadOnly Property MISC_PROFUNLEARN() As String
            Get
                Return ResourceManager.GetString("MISC_PROFUNLEARN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unlearn all ähnelt.
        '''</summary>
        Public ReadOnly Property MISC_PROFUNLEARNALL() As String
            Get
                Return ResourceManager.GetString("MISC_PROFUNLEARNALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  results ähnelt.
        '''</summary>
        Public ReadOnly Property MISC_SPELLSKILLRESULTS() As String
            Get
                Return ResourceManager.GetString("MISC_SPELLSKILLRESULTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Account has been updated successfully! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ACCOUNTUPDATECOMPLETE() As String
            Get
                Return ResourceManager.GetString("MSG_ACCOUNTUPDATECOMPLETE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Add achievement ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ADDAV() As String
            Get
                Return ResourceManager.GetString("MSG_ADDAV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Add faction ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ADDFACTION() As String
            Get
                Return ResourceManager.GetString("MSG_ADDFACTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Add new gem ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ADDGEM() As String
            Get
                Return ResourceManager.GetString("MSG_ADDGEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Add item ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ADDITEM() As String
            Get
                Return ResourceManager.GetString("MSG_ADDITEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Add quest ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ADDQUEST() As String
            Get
                Return ResourceManager.GetString("MSG_ADDQUEST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Are you sure? ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_AREYOUSURE() As String
            Get
                Return ResourceManager.GetString("MSG_AREYOUSURE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You did not select any Battle.net region. ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ARMORYREGIONNOTSET() As String
            Get
                Return ResourceManager.GetString("MSG_ARMORYREGIONNOTSET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Attention ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ATTENTION() As String
            Get
                Return ResourceManager.GetString("MSG_ATTENTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Achievement successfully added! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_AVADDED() As String
            Get
                Return ResourceManager.GetString("MSG_AVADDED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The player already has this achievement. ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_AVALREADYPRESENT() As String
            Get
                Return ResourceManager.GetString("MSG_AVALREADYPRESENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Browsing achievements... ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_BROWSINGAVS() As String
            Get
                Return ResourceManager.GetString("MSG_BROWSINGAVS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You did not set any character name. ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_CHARNAMENOTSET() As String
            Get
                Return ResourceManager.GetString("MSG_CHARNAMENOTSET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Character not found! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_CHARNOTFOUND() As String
            Get
                Return ResourceManager.GetString("MSG_CHARNOTFOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Connect to source server ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_CONNECTSOURCE() As String
            Get
                Return ResourceManager.GetString("MSG_CONNECTSOURCE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Connect to target server ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_CONNECTTARGET() As String
            Get
                Return ResourceManager.GetString("MSG_CONNECTTARGET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the selected accounts? ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_DELETEACC() As String
            Get
                Return ResourceManager.GetString("MSG_DELETEACC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the achievement %avid% from character? ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_DELETEAV() As String
            Get
                Return ResourceManager.GetString("MSG_DELETEAV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the selected characters? ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_DELETECHARACTER() As String
            Get
                Return ResourceManager.GetString("MSG_DELETECHARACTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the selected item? ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_DELETEITEM() As String
            Get
                Return ResourceManager.GetString("MSG_DELETEITEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you really want to remove this profession and its recipes? ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_DELETEPROFESSION() As String
            Get
                Return ResourceManager.GetString("MSG_DELETEPROFESSION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enter achievement id: ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ENTERAVID() As String
            Get
                Return ResourceManager.GetString("MSG_ENTERAVID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enter achievement name or id ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ENTERAVNAMEID() As String
            Get
                Return ResourceManager.GetString("MSG_ENTERAVNAMEID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enter faction id:  ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ENTERFACTIONID() As String
            Get
                Return ResourceManager.GetString("MSG_ENTERFACTIONID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enter gem id: ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ENTERGEMID() As String
            Get
                Return ResourceManager.GetString("MSG_ENTERGEMID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enter the size of this stack: ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ENTERITEMCOUNT() As String
            Get
                Return ResourceManager.GetString("MSG_ENTERITEMCOUNT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enter item id: ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ENTERITEMID() As String
            Get
                Return ResourceManager.GetString("MSG_ENTERITEMID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enter quest id: ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ENTERQUESTID() As String
            Get
                Return ResourceManager.GetString("MSG_ENTERQUESTID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enter skill id ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ENTERSKILLID() As String
            Get
                Return ResourceManager.GetString("MSG_ENTERSKILLID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enter spell id ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ENTERSPELLID() As String
            Get
                Return ResourceManager.GetString("MSG_ENTERSPELLID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ERROR() As String
            Get
                Return ResourceManager.GetString("MSG_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Faction successfully added! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_FACTIONADDED() As String
            Get
                Return ResourceManager.GetString("MSG_FACTIONADDED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The player already has reputation at this faction! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_FACTIONALREADYPRESENT() As String
            Get
                Return ResourceManager.GetString("MSG_FACTIONALREADYPRESENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Failed to connect to character database. ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_FAILEDCONNECTCHARACTER() As String
            Get
                Return ResourceManager.GetString("MSG_FAILEDCONNECTCHARACTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Failed to connect to realm/auth database. ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_FAILEDCONNECTREALM() As String
            Get
                Return ResourceManager.GetString("MSG_FAILEDCONNECTREALM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fatal error during character creation! See log for further info. ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_FATALDURINGCHARCREATION() As String
            Get
                Return ResourceManager.GetString("MSG_FATALDURINGCHARCREATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gem successfully added. ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_GEMADDED() As String
            Get
                Return ResourceManager.GetString("MSG_GEMADDED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_INFO() As String
            Get
                Return ResourceManager.GetString("MSG_INFO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Invalid achievement id! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_INVALIDAVID() As String
            Get
                Return ResourceManager.GetString("MSG_INVALIDAVID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The template file could not be loaded, because it is outdated. ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_INVALIDDATA() As String
            Get
                Return ResourceManager.GetString("MSG_INVALIDDATA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No valid E-Mail address entered! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_INVALIDEMAIL() As String
            Get
                Return ResourceManager.GetString("MSG_INVALIDEMAIL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Invalid entry! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_INVALIDENTRY() As String
            Get
                Return ResourceManager.GetString("MSG_INVALIDENTRY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Invalid faction id! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_INVALIDFACTIONID() As String
            Get
                Return ResourceManager.GetString("MSG_INVALIDFACTIONID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Invalid file name! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_INVALIDFILENAME() As String
            Get
                Return ResourceManager.GetString("MSG_INVALIDFILENAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Invalid gem id! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_INVALIDGEMID() As String
            Get
                Return ResourceManager.GetString("MSG_INVALIDGEMID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die This is not a valid glyph! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_INVALIDGLYPH() As String
            Get
                Return ResourceManager.GetString("MSG_INVALIDGLYPH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The class of the entered item does not match the source item class! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_INVALIDITEMCLASS() As String
            Get
                Return ResourceManager.GetString("MSG_INVALIDITEMCLASS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No item with this id found! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_INVALIDITEMID() As String
            Get
                Return ResourceManager.GetString("MSG_INVALIDITEMID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die This is not a valid skill id. ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_INVALIDSKILLID() As String
            Get
                Return ResourceManager.GetString("MSG_INVALIDSKILLID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die This is not a valid spell id. ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_INVALIDSPELLID() As String
            Get
                Return ResourceManager.GetString("MSG_INVALIDSPELLID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Entered URL is not valid! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_INVALIDURL() As String
            Get
                Return ResourceManager.GetString("MSG_INVALIDURL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Set item count ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_ITEMCOUNTCHANGE() As String
            Get
                Return ResourceManager.GetString("MSG_ITEMCOUNTCHANGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Loading achievements... ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_LOADINGAVS() As String
            Get
                Return ResourceManager.GetString("MSG_LOADINGAVS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You did not enter any accounts! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_NOACCOUNTENTERED() As String
            Get
                Return ResourceManager.GetString("MSG_NOACCOUNTENTERED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You did not select any accounts/characters that should be stored in a template file. Right click on accounts/characters and choose &apos;prepare for transfer&apos;. ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_NOACCOUNTSELECTED() As String
            Get
                Return ResourceManager.GetString("MSG_NOACCOUNTSELECTED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No achievements found! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_NOAVSFOUND() As String
            Get
                Return ResourceManager.GetString("MSG_NOAVSFOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pick category ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_PICKCAT() As String
            Get
                Return ResourceManager.GetString("MSG_PICKCAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Profession not known ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_PROFESSIONUNKNOWN() As String
            Get
                Return ResourceManager.GetString("MSG_PROFESSIONUNKNOWN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Quest added! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_QUESTADDED() As String
            Get
                Return ResourceManager.GetString("MSG_QUESTADDED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The character already has this quest! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_QUESTALREADYPRESENT() As String
            Get
                Return ResourceManager.GetString("MSG_QUESTALREADYPRESENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You did not set any realm name. ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_REALMNOTSET() As String
            Get
                Return ResourceManager.GetString("MSG_REALMNOTSET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you really want to reload this character? All changes will be lost! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_RELOADCHARACTER() As String
            Get
                Return ResourceManager.GetString("MSG_RELOADCHARACTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save template file ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_SAVETEMPLATE() As String
            Get
                Return ResourceManager.GetString("MSG_SAVETEMPLATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Select template file ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_SELECTTEMPLATEFILE() As String
            Get
                Return ResourceManager.GetString("MSG_SELECTTEMPLATEFILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enter quest finished status (0/1): ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_SETQSTFINISHEDSTATUS() As String
            Get
                Return ResourceManager.GetString("MSG_SETQSTFINISHEDSTATUS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enter quest rewarded status (0/1): ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_SETQSTREWARDEDSTATUS() As String
            Get
                Return ResourceManager.GetString("MSG_SETQSTREWARDEDSTATUS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die This skill is already active. ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_SKILLALREADYPRESENT() As String
            Get
                Return ResourceManager.GetString("MSG_SKILLALREADYPRESENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die This spell is already active. ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_SPELLALREADYPRESENT() As String
            Get
                Return ResourceManager.GetString("MSG_SPELLALREADYPRESENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The maximum stack size of this item is: ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_STACKLIMITREACHED() As String
            Get
                Return ResourceManager.GetString("MSG_STACKLIMITREACHED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you want to teach this profession? ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_TEACHPROFESSION() As String
            Get
                Return ResourceManager.GetString("MSG_TEACHPROFESSION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The template file has been successfully created. ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_TEMPLATEFILECREATED() As String
            Get
                Return ResourceManager.GetString("MSG_TEMPLATEFILECREATED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You cannot start more than one transmission at the same time. ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_TRANSMISSIONRUNNING() As String
            Get
                Return ResourceManager.GetString("MSG_TRANSMISSIONRUNNING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die A transmission is running! Please wait until it is completed! ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_WAITONTRANSMISSIONCOMPLETE() As String
            Get
                Return ResourceManager.GetString("MSG_WAITONTRANSMISSIONCOMPLETE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        '''</summary>
        Public ReadOnly Property MSG_WARNING() As String
            Get
                Return ResourceManager.GetString("MSG_WARNING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property namcore_header_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("namcore_header_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Public ReadOnly Property nclogo() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("nclogo", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Archaeology ähnelt.
        '''</summary>
        Public ReadOnly Property PROF_ARCHAEOLOGY() As String
            Get
                Return ResourceManager.GetString("PROF_ARCHAEOLOGY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cooking ähnelt.
        '''</summary>
        Public ReadOnly Property PROF_COOKING() As String
            Get
                Return ResourceManager.GetString("PROF_COOKING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die First Aid ähnelt.
        '''</summary>
        Public ReadOnly Property PROF_FIRSTAID() As String
            Get
                Return ResourceManager.GetString("PROF_FIRSTAID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fishing ähnelt.
        '''</summary>
        Public ReadOnly Property PROF_FISHING() As String
            Get
                Return ResourceManager.GetString("PROF_FISHING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        '''</summary>
        Public ReadOnly Property TOOLTIP_ADD() As String
            Get
                Return ResourceManager.GetString("TOOLTIP_ADD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Empty ähnelt.
        '''</summary>
        Public ReadOnly Property TOOLTIP_EMPTY() As String
            Get
                Return ResourceManager.GetString("TOOLTIP_EMPTY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        '''</summary>
        Public ReadOnly Property TOOLTIP_REMOVE() As String
            Get
                Return ResourceManager.GetString("TOOLTIP_REMOVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;root&gt;
        '''  &lt;!-- 
        '''    Microsoft ResX Schema 
        '''    
        '''    Version 2.0
        '''    
        '''    The primary goals of this format is to allow a simple XML format 
        '''    that is mostly human readable. The generation and parsing of the 
        '''    various data types are done through the TypeConverter classes 
        '''    associated with the data types.
        '''    
        '''    Example:
        '''    
        '''    ... ado.net/XML headers &amp; schema ...
        '''    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        '''    &lt;resheader n [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property UserMessages() As String
            Get
                Return ResourceManager.GetString("UserMessages", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
