'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.18052
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.ComponentModel

Namespace My

    <Localizable(False), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Partial Public NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)

#Region "Funktion zum automatischen Speichern von My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region

        Public Shared ReadOnly Property [Default]() As MySettings
            Get

#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("de")> _
        Public Property language() As String
            Get
                Return CType(Me("language"), String)
            End Get
            Set(value As String)
                Me("language") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property proxy_host() As String
            Get
                Return CType(Me("proxy_host"), String)
            End Get
            Set(value As String)
                Me("proxy_host") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("80")> _
        Public Property proxy_port() As Integer
            Get
                Return CType(Me("proxy_port"), Integer)
            End Get
            Set(value As Integer)
                Me("proxy_port") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property proxy_uname() As String
            Get
                Return CType(Me("proxy_uname"), String)
            End Get
            Set(value As String)
                Me("proxy_uname") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property proxy_pass() As String
            Get
                Return CType(Me("proxy_pass"), String)
            End Get
            Set(value As String)
                Me("proxy_pass") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("True")> _
        Public Property proxy_defaultCredentials() As Boolean
            Get
                Return CType(Me("proxy_defaultCredentials"), Boolean)
            End Get
            Set(value As Boolean)
                Me("proxy_defaultCredentials") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("False")> _
        Public Property proxy_enabled() As Boolean
            Get
                Return CType(Me("proxy_enabled"), Boolean)
            End Get
            Set(value As Boolean)
                Me("proxy_enabled") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("False")> _
        Public Property proxy_detect() As Boolean
            Get
                Return CType(Me("proxy_detect"), Boolean)
            End Get
            Set(value As Boolean)
                Me("proxy_detect") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property fullproxy() As Global.System.Net.WebProxy
            Get
                Return CType(Me("fullproxy"), Global.System.Net.WebProxy)
            End Get
            Set(value As Global.System.Net.WebProxy)
                Me("fullproxy") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("localhost")> _
        Public Property server_address() As String
            Get
                Return CType(Me("server_address"), String)
            End Get
            Set(value As String)
                Me("server_address") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("3306")> _
        Public Property server_port() As Integer
            Get
                Return CType(Me("server_port"), Integer)
            End Get
            Set(value As Integer)
                Me("server_port") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("root")> _
        Public Property server_login() As String
            Get
                Return CType(Me("server_login"), String)
            End Get
            Set(value As String)
                Me("server_login") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property server_pass() As String
            Get
                Return CType(Me("server_pass"), String)
            End Get
            Set(value As String)
                Me("server_pass") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("auth")> _
        Public Property server_authdb() As String
            Get
                Return CType(Me("server_authdb"), String)
            End Get
            Set(value As String)
                Me("server_authdb") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("characters")> _
        Public Property server_chardb() As String
            Get
                Return CType(Me("server_chardb"), String)
            End Get
            Set(value As String)
                Me("server_chardb") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("True")> _
        Public Property server_defaultconn() As Boolean
            Get
                Return CType(Me("server_defaultconn"), Boolean)
            End Get
            Set(value As Boolean)
                Me("server_defaultconn") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("localhost")> _
        Public Property server_ncremoteaddress() As String
            Get
                Return CType(Me("server_ncremoteaddress"), String)
            End Get
            Set(value As String)
                Me("server_ncremoteaddress") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("")> _
        Public Property server_nclogin() As String
            Get
                Return CType(Me("server_nclogin"), String)
            End Get
            Set(value As String)
                Me("server_nclogin") = Value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.NCFramework.My.MySettings
            Get
                Return Global.NCFramework.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
