'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.18052
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("libnc.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die AchievementId£NameDE£NameEN£DescriptionDE£DescriptionEN£CategoryId£SpellId
        '''6£Stufe 10£Level 10£Erreicht Stufe 10.£Reach level 10.£92£3268
        '''33£Rauf und runter in der Tundra£Nothing Boring About Borean£Schließt 130 Quests der Boreanischen Tundra ab.£Complete 130 quests in Borean Tundra.£14863£3336
        '''42£Erkundet die Östlichen Königreiche£Explore Eastern Kingdoms£Erkundet die Regionen der Östlichen Königreiche.£Explore the regions of Eastern Kingdoms.£97£3490
        '''57£Tode im Alteractal£Deaths in Alterac Valley£Tode [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property Achievement() As String
            Get
                Return ResourceManager.GetString("Achievement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die CategoryId£MainCatId£NameDE£NameEN
        '''92£-1£Allgemein£General
        '''123£122£Arenen£Arenas
        '''130£1£Charakter£Character
        '''135£128£Kreaturen£Creatures
        '''140£130£Vermögen£Wealth
        '''152£21£Gewertete Arenen£Rated Arenas
        '''160£155£Mondfest£Lunar Festival
        '''170£169£Kochkunst£Cooking
        '''178£132£Sekundäre Fertigkeiten£Secondary Skills
        '''14777£97£Östliche Königreiche£Eastern Kingdoms
        '''14804£95£Kriegshymnenschlucht£Warsong Gulch
        '''14808£168£Classic£Classic
        '''14821£14807£Classic£Classic
        '''14861£96£Östliche Königreiche£Eastern Kingdoms
        '''148 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property AchievementCategory() As String
            Get
                Return ResourceManager.GetString("AchievementCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die FactionId£Index£NameDE£NameEN
        '''1£-1£SPIELER, Mensch£PLAYER, Human
        '''2£-1£SPIELER, Orc£PLAYER, Orc
        '''3£-1£SPIELER, Zwerg£PLAYER, Dwarf
        '''4£-1£SPIELER, Nachtelf£PLAYER, Night Elf
        '''5£-1£SPIELER, Untoter£PLAYER, Undead
        '''6£-1£SPIELER, Tauren£PLAYER, Tauren 
        '''7£-1£Kreatur£Creature
        '''8£-1£SPIELER, Gnom£PLAYER, Gnome
        '''9£-1£SPIELER, Troll£PLAYER, Troll
        '''14£-1£Monster£Monster
        '''15£-1£Bruderschaft der Defias£Defias Brotherhood
        '''16£-1£Gnoll - Flusspfoten£Gnoll - Riverpaw
        '''17£-1£Gnoll - Rotkammgebirge£Gnoll - Redridge
        '''18£-1 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property Faction() As String
            Get
                Return ResourceManager.GetString("Faction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die GlyphId£SpellId£Icon
        '''2£52084£3098
        '''21£12320£0
        '''22£12297£0
        '''61£46831£0
        '''81£52084£0
        '''82£52085£0
        '''101£0£0
        '''121£46487£2681
        '''141£54292£3115
        '''161£54810£3114
        '''162£54811£3113
        '''163£54812£3312
        '''164£54813£3124
        '''165£54815£3129
        '''166£54818£3112
        '''167£54821£3128
        '''168£54824£3123
        '''169£54832£3121
        '''170£54733£3127
        '''171£54743£3098
        '''172£54754£3125
        '''173£54825£3119
        '''174£54826£3120
        '''175£54845£3117
        '''176£54830£3122
        '''177£54831£3118
        '''178£54828£3116
        '''179£54756£3126
        '''180£54829£3110
        '''181£54760£3115
        '''182£54912£0
        '''183£54922£3128
        '''184£54925£ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property GlyphProperties0() As String
            Get
                Return ResourceManager.GetString("GlyphProperties0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die GlyphId£SpellId£Icon
        '''161£54810£3114
        '''162£54811£3113
        '''163£54812£3312
        '''164£54813£3124
        '''165£54815£3129
        '''166£54818£3112
        '''167£54821£3128
        '''168£54824£3123
        '''169£54832£3121
        '''170£54733£3127
        '''171£54743£3098
        '''172£54754£3125
        '''173£54825£3119
        '''174£54826£3120
        '''175£54845£3117
        '''176£54830£3122
        '''177£54831£3118
        '''178£54828£3116
        '''179£54756£3126
        '''180£54829£3110
        '''181£54760£3115
        '''183£54922£3128
        '''184£54925£3121
        '''185£54923£3112
        '''186£54924£3115
        '''187£54926£3117
        '''188£54927£3110
        '''189£54928£3119
        '''190£89401£3118
        '''191£54930£3125
        '''192£54931£ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property GlyphProperties1() As String
            Get
                Return ResourceManager.GetString("GlyphProperties1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die GlyphId£SpellId£Icon
        '''161£54810£3114
        '''162£54811£3113
        '''163£54812£3312
        '''164£114338£3124
        '''165£114234£3129
        '''166£116186£3112
        '''167£54821£3128
        '''168£114300£3123
        '''169£54832£3121
        '''170£54733£3127
        '''171£116218£3098
        '''172£17076£3125
        '''173£54825£3119
        '''174£114228£3120
        '''175£146655£3117
        '''176£114333£3122
        '''177£54831£3118
        '''178£116216£3116
        '''179£116203£3126
        '''180£127540£3110
        '''181£54760£3115
        '''183£54922£3128
        '''184£146955£3121
        '''185£54923£3112
        '''186£54924£3115
        '''187£54926£3117
        '''188£54927£3110
        '''189£54928£3119
        '''190£89401£3118
        '''191£54930£3125 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property GlyphProperties2() As String
            Get
                Return ResourceManager.GetString("GlyphProperties2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property INV_Misc_QuestionMark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INV_Misc_QuestionMark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ItemId£Class£SubClass
        '''17£4£4
        '''25£2£7
        '''35£2£10
        '''36£2£4
        '''37£2£0
        '''38£4£0
        '''39£4£1
        '''40£4£1
        '''41£4£0
        '''42£4£0
        '''43£4£1
        '''44£4£1
        '''45£4£0
        '''46£4£0
        '''47£4£1
        '''48£4£1
        '''49£4£0
        '''50£4£0
        '''51£4£1
        '''52£4£1
        '''53£4£0
        '''54£4£0
        '''55£4£1
        '''56£4£1
        '''57£4£1
        '''58£4£0
        '''59£4£1
        '''60£4£2
        '''61£4£2
        '''77£4£1
        '''79£4£1
        '''80£4£1
        '''85£4£2
        '''86£4£0
        '''87£4£0
        '''88£4£1
        '''89£4£0
        '''90£4£0
        '''91£4£1
        '''92£4£0
        '''93£4£0
        '''94£4£0
        '''95£4£0
        '''97£4£1
        '''98£4£0
        '''99£4£0
        '''100£4£1
        '''101£4£0
        '''102£4£0
        '''103£4£0
        '''104£4£1
        '''105£4£0
        '''113£4£1
        '''114£4£0
        '''115£4£0
        '''117£0£5
        '''118£0£1
        '''119£4£0
        '''120£4£1
        '''121 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property Item() As String
            Get
                Return ResourceManager.GetString("Item", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ItemId£Icon
        '''224£INV_Jewelry_Ring_03
        '''233£INV_Boots_01
        '''242£INV_Boots_01
        '''245£INV_Boots_01
        '''249£INV_Boots_01
        '''253£INV_Boots_01
        '''257£INV_Boots_01
        '''261£INV_Boots_01
        '''292£INV_Potion_08
        '''295£INV_Boots_02
        '''302£INV_Boots_01
        '''310£INV_Belt_01
        '''311£INV_Boots_01
        '''362£INV_Misc_Bag_01
        '''365£INV_Pants_02
        '''368£INV_Pants_02
        '''369£INV_Shirt_01
        '''370£INV_Pants_02
        '''371£INV_Shirt_01
        '''372£INV_Pants_02
        '''373£INV_Shirt_01
        '''374£INV_Pants_02
        '''383£INV_Shirt_01
        '''386£INV_Pants_02
        '''387£INV_Shirt_01
        '''392£INV_Pants_02
        '''393£INV_Shirt_01
        '''394 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property ItemDisplayInfo() As String
            Get
                Return ResourceManager.GetString("ItemDisplayInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ItemId£Quality£InventoryType£MaxStack£SlotCount£SpellId£ItemNameDE£ItemNameEN£BagFamily
        '''17£0£4£1£0£7£Martinsfuror£Martin Fury£0
        '''25£1£21£1£0£0£Abgenutztes Kurzschwert£Worn Shortsword£0
        '''35£1£17£1£0£0£Gebogener Stab£Bent Staff£0
        '''36£1£21£1£0£0£Abgenutzter Streitkolben£Worn Mace£0
        '''37£1£21£1£0£0£Abgenutzte Axt£Worn Axe£0
        '''38£1£4£1£0£0£Rekrutenhemd£Recruit&apos;s Shirt£0
        '''39£1£7£1£0£0£Rekrutenhose£Recruit&apos;s Pants£0
        '''40£1£8£1£0£0£Rekrutenstiefel£Recruit&apos;s Boots£0
        '''43£1£8£1£0£0£Knappenstiefel£Squire&apos;s Boots£0
        '''44£1£ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property ItemSparse() As String
            Get
                Return ResourceManager.GetString("ItemSparse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die racemask£classmask£Spell£Note
        '''0£39£202£Two-Handed Swords
        '''0£111£196£One-Handed Axes
        '''0£1£2457£Battle Stance
        '''0£1£88161£Strike
        '''0£13£5011£Crossbows
        '''0£9£3018£Shoot
        '''0£103£197£Two-Handed Axes
        '''0£1501£1180£Daggers
        '''0£0£45927£Summon Friend
        '''0£0£6478£Opening
        '''0£0£6603£Auto Attack
        '''0£0£22027£Remove Insignia
        '''0£0£22810£Opening - No Text
        '''0£0£21651£Opening
        '''0£0£21652£Closing
        '''0£0£2382£Generic
        '''0£0£3365£Opening
        '''0£0£3050£Detect
        '''0£0£9125£Generic
        '''0£0£8386£Attacking
        '''0£0£7266£Duel
        '''0£0£7267£Grovel
        '''0£0£7355£Stuck
        '''0 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property PlayerCreateInfo() As String
            Get
                Return ResourceManager.GetString("PlayerCreateInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Id£TitleDE£TitleEN
        '''1£Kanrethads Quest£Kanrethad&apos;s Quest
        '''2£Klaue von Scharfkralle£Sharptalon&apos;s Claw
        '''5£Bibbers&apos; knurrender Magen£Jitters&apos; Growling Gut
        '''6£Kopfgeld auf Garrick Schleichfuß£Bounty on Garrick Padfoot
        '''8£Ein Schurkenhandel£A Rogue&apos;s Deal
        '''9£Tod auf den Feldern£The Killing Fields
        '''10£Die Erlösung von Kieselschliff£The Scrimshank Redemption
        '''11£Kopfgeld auf die Flusspfotengnolle£Riverpaw Gnoll Bounty
        '''12£Die Volksmiliz£The People&apos;s Militia
        '''13£Die Volksmiliz£The People&apos;s Militia
        '''14£Die Volksmili [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property questname() As String
            Get
                Return ResourceManager.GetString("questname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SkillId£NameDE£NameEN
        '''43£Schwerter£Swords
        '''44£Äxte£Axes
        '''45£Bögen£Bows
        '''46£Schusswaffen£Guns
        '''54£Streitkolben£Maces
        '''55£Zweihandschwerter£Two-Handed Swords
        '''95£Verteidigung£Defense
        '''98£Sprache: Gemeinsprache£Language: Common
        '''101£Volksfähigkeit - Zwerge£Dwarven Racial
        '''109£Sprache: Orcisch£Language: Orcish
        '''111£Sprache: Zwergisch£Language: Dwarven
        '''113£Sprache: Darnassisch£Language: Darnassian
        '''115£Sprache: Taurahe£Language: Taurahe
        '''118£Beidhändigkeit£Dual Wield
        '''124£Volksfähigkeit - Tauren£Tauren Racial        ''' [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property SkillLine() As String
            Get
                Return ResourceManager.GetString("SkillLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SpellId£SpellNameDE£SpellNameEN£DescriptionDE
        '''1£Word of Recall (OLD)£Word of Recall (OLD)£
        '''3£Word of Mass Recall (OLD)£Word of Mass Recall (OLD)£
        '''4£Wort des Rückrufs Anderer£Word of Recall Other£
        '''5£Todesberührung£Death Touch£isavaliable
        '''7£Selbstmord£Suicide£isavaliable
        '''10£Blizzard£Blizzard£isavaliable
        '''13£Schwimmtempo (TEST)£Swim Speed (TEST)£
        '''14£Manasauger£Mana Drain£
        '''17£Machtwort: Schild£Power Word: Shield£isavaliable
        '''18£Selbstheilung£Heal Self (TEST)£
        '''22£Super-Essen (TEST)£Super Food (TEST)£
        '''2 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property Spell() As String
            Get
                Return ResourceManager.GetString("Spell", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ItemId£EffectId£SpellId
        '''0£0£1
        '''0£0£3
        '''0£0£4
        '''0£0£5
        '''0£0£7
        '''0£0£10
        '''0£0£10
        '''0£0£10
        '''0£0£12
        '''0£0£13
        '''0£0£14
        '''0£127£17
        '''0£0£18
        '''0£0£22
        '''0£0£24
        '''0£0£25
        '''0£0£26
        '''0£8£27
        '''0£0£31
        '''0£0£33
        '''0£0£34
        '''0£0£35
        '''0£1£43
        '''0£75£45
        '''0£0£53
        '''0£0£53
        '''0£0£53
        '''0£0£56
        '''0£0£59
        '''0£917504£65
        '''0£0£66
        '''0£0£66
        '''0£18£71
        '''0£0£75
        '''0£127£77
        '''0£1£77
        '''0£0£78
        '''0£0£78
        '''0£90£81
        '''0£0£89
        '''0£0£89
        '''0£0£89
        '''0£1£91
        '''0£0£96
        '''0£0£96
        '''0£0£99
        '''0£1£99
        '''0£0£100
        '''0£0£100
        '''0£0£100
        '''0£0£100
        '''0£0£101
        '''0£0£101
        '''0£0£101
        '''0£90£107
        '''0£90£108
        '''0£0£110
        '''0£1£111
        '''0£0 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property SpellEffect() As String
            Get
                Return ResourceManager.GetString("SpellEffect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die EffectId£GemId£Points1£Points2£Points3£EffectNameDE£EffectNameEN
        '''2£0£0£0£0£Frostbrand£Frostbrand
        '''5£0£100£0£0£Flammenzunge£Flametongue
        '''13£0£3£0£0£Geschärft (+$k1 Schaden)£Sharpened (+$k1 Damage)
        '''14£0£4£0£0£Geschärft (+$k1 Schaden)£Sharpened (+$k1 Damage)
        '''15£0£8£0£0£Verstärkt (+$k1 Rüstung)£Reinforced (+$k1 Armor)
        '''16£0£16£0£0£Verstärkt (+$k1 Rüstung)£Reinforced (+$k1 Armor)
        '''17£0£24£0£0£Verstärkt (+$k1 Rüstung)£Reinforced (+$k1 Armor)
        '''18£0£32£0£0£Verstärkt (+$k1 Rüstung)£Reinforced (+$k1 Armor)
        '''19£0£2 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property SpellEnchant() As String
            Get
                Return ResourceManager.GetString("SpellEnchant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SpellId£Icon
        '''1£Trade_Engineering
        '''9£Spell_Shadow_BlackPlague
        '''10£Spell_Nature_NaturesBlessing
        '''11£Spell_Fire_Fire
        '''12£Spell_Fire_Fireball
        '''13£Spell_Nature_MagicImmunity
        '''14£Spell_Frost_Frost
        '''15£Spell_Frost_Stun
        '''16£Spell_Fire_FireArmor
        '''17£Spell_Frost_IceShock
        '''18£Spell_Fire_FireBolt
        '''19£Spell_Nature_LightningShield
        '''20£Spell_Nature_StrangleVines
        '''21£Spell_Nature_FarSight
        '''22£Spell_Shadow_ShadeTrueSight
        '''23£Ability_ShockWave
        '''24£Spell_Nature_Reincarnation
        '''25£Ability_ThunderBolt
        '''26£Ability_MeleeDamage
        '''2 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property SpellIcon() As String
            Get
                Return ResourceManager.GetString("SpellIcon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die TalentId£Rang1£Rang2£Rang3£Rang4£Rang5
        '''27£11078£11080£0£0£0
        '''1141£18459£18460£54734£0£0
        '''26£11069£12338£12339£12340£12341
        '''34£11119£11120£12846£12847£12848
        '''2212£54747£54749£0£0£0
        '''31£11108£12349£12350£0£0
        '''28£11100£12353£0£0£0
        '''30£11103£12357£12358£0£0
        '''29£11366£0£0£0£0
        '''23£11083£12351£0£0£0
        '''25£11095£12872£12873£0£0
        '''24£11094£13043£0£0£0
        '''1639£29074£29075£29076£0£0
        '''1730£31638£31639£31640£0£0
        '''33£11115£11367£11368£0£0
        '''32£11113£0£0£0£0
        '''1731£31641£31642£0£0£0
        '''35£11124£12378£12398£12399£12400
        '''1733£34293 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property talent() As String
            Get
                Return ResourceManager.GetString("talent", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
